services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-broker
    ports:
      - "1883:1883" # MQTT
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  evaluation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation
    volumes:
      # mounts project files into the container via volumes instead of copying them in Dockerfile
      # to allow to run the most-up-to-date code without rebuilding the image
      - ./core:/app/core
      - ./distributed:/app/distributed
      - ./examples:/app/examples
      - ./evaluation:/app/evaluation
      - ./RunExperiments.sc:/app/RunExperiments.sc
      - ./requirements.txt:/app/requirements.txt
      - ./plot_results.py:/app/plot_results.py
